# Generated by Django 3.1.8 on 2021-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdbapp', '0008_auto_20210418_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(default=77),
            preserve_default=False,
        ),
    ]
