# Generated by Django 3.0.8 on 2021-04-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdbapp', '0002_auto_20210403_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='help',
            new_name='helping',
        ),
    ]
